-- /mnt/ext1/Books/Clear, James/Atomic Habits_ An Easy & Proven Way to Build Good Habits & Break Bad Ones - James Clear.sdr/metadata.epub.lua
return {
    ["annotations"] = {
        [1] = {
            ["chapter"] = "10: How to Find and Fix the Causes of Your Bad Habits",
            ["color"] = "gray",
            ["datetime"] = "2025-01-30 16:52:58",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[19]/body/div[1]/p[27]/text()[1].0",
            ["pageno"] = 189,
            ["pos0"] = "/body/DocFragment[19]/body/div[1]/p[27]/text()[1].0",
            ["pos1"] = "/body/DocFragment[19]/body/div[1]/p[27]/text()[4].11",
            ["text"] = "Desire is the difference between where you are now and where you want to be in the future. Even the tiniest action is tinged with the motivation to feel differently than you do in the moment. When you binge-eat or light up or browse social media, what you really want is not a potato chip or a cigarette or a bunch of likes. What you really want is to feel different.",
        },
        [2] = {
            ["chapter"] = "10: How to Find and Fix the Causes of Your Bad Habits",
            ["color"] = "gray",
            ["datetime"] = "2025-01-30 16:54:53",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[19]/body/div[1]/p[29]/text().0",
            ["pageno"] = 190,
            ["pos0"] = "/body/DocFragment[19]/body/div[1]/p[29]/text().0",
            ["pos1"] = "/body/DocFragment[19]/body/div[1]/p[29]/text().513",
            ["text"] = "To summarize, the specific cravings you feel and habits you perform are really an attempt to address your fundamental underlying motives. Whenever a habit successfully addresses a motive, you develop a craving to do it again. In time, you learn to predict that checking social media will help you feel loved or that watching YouTube will allow you to forget your fears. Habits are attractive when we associate them with positive feelings, and we can use this insight to our advantage rather than to our detriment.",
        },
        [3] = {
            ["chapter"] = "11: Walk Slowly, but Never Backward",
            ["color"] = "gray",
            ["datetime"] = "2025-09-11 14:18:55",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[21]/body/div/p[6]/text().2",
            ["pageno"] = 200,
            ["pos0"] = "/body/DocFragment[21]/body/div/p[6]/text().2",
            ["pos1"] = "/body/DocFragment[21]/body/div/p[6]/text().261",
            ["text"] = "refer to this as the difference between being in motion and taking action. The two ideas sound similar, but they’re not the same. When you’re in motion, you’re planning and strategizing and learning. Those are all good things, but they don’t produce a result.",
        },
        [4] = {
            ["chapter"] = "11: Walk Slowly, but Never Backward",
            ["color"] = "gray",
            ["datetime"] = "2025-09-11 14:19:18",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[21]/body/div/p[7]/text().0",
            ["pageno"] = 201,
            ["pos0"] = "/body/DocFragment[21]/body/div/p[7]/text().0",
            ["pos1"] = "/body/DocFragment[21]/body/div/p[7]/text().345",
            ["text"] = "Action, on the other hand, is the type of behavior that will deliver an outcome. If I outline twenty ideas for articles I want to write, that’s motion. If I actually sit down and write an article, that’s action. If I search for a better diet plan and read a few books on the topic, that’s motion. If I actually eat a healthy meal, that’s action.",
        },
        [5] = {
            ["chapter"] = "11: Walk Slowly, but Never Backward",
            ["color"] = "gray",
            ["datetime"] = "2025-09-11 14:24:41",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[21]/body/div/p[12]/text().0",
            ["pageno"] = 202,
            ["pos0"] = "/body/DocFragment[21]/body/div/p[12]/text().0",
            ["pos1"] = "/body/DocFragment[21]/body/div/p[12]/text().247",
            ["text"] = "If you want to master a habit, the key is to start with repetition, not perfection. You don’t need to map out every feature of a new habit. You just need to practice it. This is the first takeaway of the 3rd Law: you just need to get your reps in.",
        },
        [6] = {
            ["chapter"] = "11: Walk Slowly, but Never Backward",
            ["color"] = "gray",
            ["datetime"] = "2025-09-11 14:31:32",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[21]/body/div/p[20]/text()[1].165",
            ["pageno"] = 207,
            ["pos0"] = "/body/DocFragment[21]/body/div/p[20]/text()[1].165",
            ["pos1"] = "/body/DocFragment[21]/body/div/p[20]/text()[3].40",
            ["text"] = "shape of these charts, which scientists call learning curves, reveals an important truth about behavior change: habits form based on frequency, not time",
        },
        [7] = {
            ["chapter"] = "12: The Law of Least Effort",
            ["color"] = "gray",
            ["datetime"] = "2025-09-11 14:54:55",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[22]/body/div/p[12]/text()[1].54",
            ["pageno"] = 216,
            ["pos0"] = "/body/DocFragment[22]/body/div/p[12]/text()[1].54",
            ["pos1"] = "/body/DocFragment[22]/body/div/p[12]/text()[4].115",
            ["text"] = "The problem is that some days you feel like doing the hard work and some days you feel like giving in. On the tough days, it’s crucial to have as many things working in your favor as possible so that you can overcome the challenges life naturally throws your way. The less friction you face, the easier it is for your stronger self to emerge. The idea behind make it easy is not to only do easy things. The idea is to make it as easy as possible in the moment to do things that payoff in the long run.",
        },
        [8] = {
            ["chapter"] = "12: The Law of Least Effort",
            ["color"] = "gray",
            ["datetime"] = "2025-09-11 18:54:54",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[22]/body/div/p[24]/text().0",
            ["pageno"] = 220,
            ["pos0"] = "/body/DocFragment[22]/body/div/p[24]/text().0",
            ["pos1"] = "/body/DocFragment[22]/body/div/p[24]/text().279",
            ["text"] = "The central idea is to create an environment where doing the right thing is as easy as possible. Much of the battle of building better habits comes down to finding ways to reduce the friction associated with our good habits and increase the friction associated with our bad ones.",
        },
        [9] = {
            ["chapter"] = "12: The Law of Least Effort",
            ["color"] = "gray",
            ["datetime"] = "2025-09-11 19:04:04",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[22]/body/div/ul[2]/li[1]/p/text().0",
            ["pageno"] = 225,
            ["pos0"] = "/body/DocFragment[22]/body/div/ul[2]/li[1]/p/text().0",
            ["pos1"] = "/body/DocFragment[22]/body/div/ul[2]/li[1]/p/text().133",
            ["text"] = "Human behavior follows the Law of Least Effort. We will naturally gravitate toward the option that requires the least amount of work.",
        },
        [10] = {
            ["chapter"] = "12: The Law of Least Effort",
            ["color"] = "gray",
            ["datetime"] = "2025-09-11 19:04:08",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[22]/body/div/ul[2]/li[2]/p/text().0",
            ["pageno"] = 225,
            ["pos0"] = "/body/DocFragment[22]/body/div/ul[2]/li[2]/p/text().0",
            ["pos1"] = "/body/DocFragment[22]/body/div/ul[2]/li[2]/p/text().73",
            ["text"] = "Create an environment where doing the right thing is as easy as possible.",
        },
        [11] = {
            ["chapter"] = "13: How to Stop Procrastinating by Using the Two-Minute Rule",
            ["color"] = "gray",
            ["datetime"] = "2025-09-11 19:17:51",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[23]/body/div/p[17]/text()[1].57",
            ["pageno"] = 233,
            ["pos0"] = "/body/DocFragment[23]/body/div/p[17]/text()[1].57",
            ["pos1"] = "/body/DocFragment[23]/body/div/p[17]/text()[1].274",
            ["text"] = "one page or meditating for one minute or making one sales call. But the point is not to do one thing. The point is to master the habit of showing up. The truth is, a habit must be established before it can be improved",
        },
        [12] = {
            ["chapter"] = "13: How to Stop Procrastinating by Using the Two-Minute Rule",
            ["color"] = "gray",
            ["datetime"] = "2025-09-11 19:53:59",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[23]/body/div/ul[2]/li[2]/p/text().0",
            ["pageno"] = 239,
            ["pos0"] = "/body/DocFragment[23]/body/div/ul[2]/li[2]/p/text().0",
            ["pos1"] = "/body/DocFragment[23]/body/div/ul[2]/li[2]/p/text().159",
            ["text"] = "Many habits occur at decisive moments—choices that are like a fork in the road—and either send you in the direction of a productive day or an unproductive one.",
        },
        [13] = {
            ["chapter"] = "13: How to Stop Procrastinating by Using the Two-Minute Rule",
            ["color"] = "gray",
            ["datetime"] = "2025-09-11 19:54:16",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[23]/body/div/ul[2]/li[4]/p/text().0",
            ["pageno"] = 239,
            ["pos0"] = "/body/DocFragment[23]/body/div/ul[2]/li[4]/p/text().0",
            ["pos1"] = "/body/DocFragment[23]/body/div/ul[2]/li[4]/p/text().161",
            ["text"] = "The more you ritualize the beginning of a process, the more likely it becomes that you can slip into the state of deep focus that is required to do great things.",
        },
        [14] = {
            ["chapter"] = "14: How to Make Good Habits Inevitable and Bad Habits Impossible",
            ["datetime"] = "2025-09-16 14:49:32",
            ["page"] = "/body/DocFragment[24]/body/div[1]/div[1]/img.0",
            ["pageno"] = 240,
            ["text"] = "in 14: How to Make Good Habits Inevitable and Bad Habits Impossible",
        },
        [15] = {
            ["chapter"] = "14: How to Make Good Habits Inevitable and Bad Habits Impossible",
            ["datetime"] = "2025-09-16 15:03:26",
            ["page"] = "/body/DocFragment[24]/body/div[1]/p[18]/text().337",
            ["pageno"] = 246,
            ["text"] = "in 14: How to Make Good Habits Inevitable and Bad Habits Impossible",
        },
        [16] = {
            ["chapter"] = "14: How to Make Good Habits Inevitable and Bad Habits Impossible",
            ["color"] = "gray",
            ["datetime"] = "2025-09-16 15:03:53",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[24]/body/div[1]/p[19]/b/text().0",
            ["pageno"] = 246,
            ["pos0"] = "/body/DocFragment[24]/body/div[1]/p[19]/b/text().0",
            ["pos1"] = "/body/DocFragment[24]/body/div[1]/p[19]/b/text().40",
            ["text"] = "ONETIME ACTIONS THAT LOCK IN GOOD HABITS",
        },
        [17] = {
            ["chapter"] = "15: The Cardinal Rule of Behavior Change",
            ["color"] = "gray",
            ["datetime"] = "2025-09-16 17:04:53",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[26]/body/div/p[29]/text()[2].147",
            ["pageno"] = 265,
            ["pos0"] = "/body/DocFragment[26]/body/div/p[29]/text()[2].147",
            ["pos1"] = "/body/DocFragment[26]/body/div/p[29]/span[2]/a/text().1",
            ["text"] = "As a general rule, the more immediate pleasure you get from an action, the more strongly you should question whether it aligns with your long-term goals.*",
        },
        [18] = {
            ["chapter"] = "15: The Cardinal Rule of Behavior Change",
            ["color"] = "gray",
            ["datetime"] = "2025-09-16 18:10:04",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[26]/body/div/p[40]/text().0",
            ["pageno"] = 269,
            ["pos0"] = "/body/DocFragment[26]/body/div/p[40]/text().0",
            ["pos1"] = "/body/DocFragment[26]/body/div/p[40]/text().280",
            ["text"] = "It is worth noting that it is important to select short-term rewards that reinforce your identity rather than ones that conflict with it. Buying a new jacket is fine if you’re trying to lose weight or read more books, but it doesn’t work if you’re trying to budget and save money.",
        },
        [19] = {
            ["chapter"] = "16: How to Stick with Good Habits Every Day",
            ["color"] = "gray",
            ["datetime"] = "2025-09-16 18:35:29",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[27]/body/div/p[32]/text()[1].0",
            ["pageno"] = 281,
            ["pos0"] = "/body/DocFragment[27]/body/div/p[32]/text()[1].0",
            ["pos1"] = "/body/DocFragment[27]/body/div/p[32]/text()[2].71",
            ["text"] = "The first mistake is never the one that ruins you. It is the spiral of repeated mistakes that follows. Missing once is an accident. Missing twice is the start of a new habit.",
        },
        [20] = {
            ["chapter"] = "18: The Truth About Talent (When Genes Matter and When They Don’t)",
            ["color"] = "gray",
            ["datetime"] = "2025-09-19 17:41:17",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[30]/body/div/p[7]/text().0",
            ["pageno"] = 302,
            ["pos0"] = "/body/DocFragment[30]/body/div/p[7]/text().0",
            ["pos1"] = "/body/DocFragment[30]/body/div/p[7]/text().291",
            ["text"] = "The secret to maximizing your odds of success is to choose the right field of competition. This is just as true with habit change as it is with sports and business. Habits are easier to perform, and more satisfying to stick with, when they align with your natural inclinations and abilities.",
        },
        [21] = {
            ["chapter"] = "18: The Truth About Talent (When Genes Matter and When They Don’t)",
            ["color"] = "gray",
            ["datetime"] = "2025-09-21 19:12:15",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[30]/body/div/div[2]/p[1]/b/text().0",
            ["pageno"] = 311,
            ["pos0"] = "/body/DocFragment[30]/body/div/div[2]/p[1]/b/text().0",
            ["pos1"] = "/body/DocFragment[30]/body/div/div[2]/p[1]/text().293",
            ["text"] = "What feels like fun to me, but work to others? The mark of whether you are made for a task is not whether you love it but whether you can handle the pain of the task easier than most people. When are you enjoying yourself while other people are complaining? The work that hurts you less than it hurts others is the work you were made to do.",
        },
        [22] = {
            ["chapter"] = "18: The Truth About Talent (When Genes Matter and When They Don’t)",
            ["color"] = "gray",
            ["datetime"] = "2025-09-21 19:13:54",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[30]/body/div/div[2]/p[4]/b/text().0",
            ["pageno"] = 312,
            ["pos0"] = "/body/DocFragment[30]/body/div/div[2]/p[4]/b/text().0",
            ["pos1"] = "/body/DocFragment[30]/body/div/div[2]/p[4]/text().440",
            ["text"] = "What comes naturally to me? For just a moment, ignore what you have been taught. Ignore what society has told you. Ignore what others expect of you. Look inside yourself and ask, “What feels natural to me? When have I felt alive? When have I felt like the real me?” No internal judgments or people-pleasing. No second-guessing or self-criticism. Just feelings of engagement and enjoyment. Whenever you feel authentic and genuine, you are headed in the right direction.",
        },
    },
    ["cache_file_path"] = "./cache/cr3cache/Atomic_Habit-s_Clear.epub.65be65cc.1.cr3",
    ["config_panel_index"] = 2,
    ["copt_b_page_margin"] = 30,
    ["copt_block_rendering_mode"] = 2,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 0.5,
    ["copt_font_gamma"] = 15,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_font_size"] = 19,
    ["copt_h_page_margins"] = {
        [1] = 30,
        [2] = 30,
    },
    ["copt_line_spacing"] = 125,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 96,
    ["copt_rotation_mode"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_status_line"] = 1,
    ["copt_sync_t_b_page_margins"] = 0,
    ["copt_t_page_margin"] = 30,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 1,
    ["copt_word_expansion"] = 0,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["cre_dom_version"] = 20240114,
    ["css"] = "./data/epub.css",
    ["doc_pages"] = 470,
    ["doc_path"] = "/mnt/ext1/Books/Clear, James/Atomic Habits_ An Easy & Proven Way to Build Good Habits & Break Bad Ones - James Clear.epub",
    ["doc_props"] = {
        ["authors"] = "James Clear",
        ["description"] = "<div><p><strong><em>*The instant </em></strong>**New York Times<strong><em>*</em> bestseller</strong> </p><p><strong><em>Tiny Changes, Remarkable Results</em></strong>** </p><p>No matter your goals, <em>Atomic Habits</em> offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results. </p><p>If you're having trouble changing your habits, the problem isn't you. The problem is your system. Bad habits repeat themselves again and again not because you don't want to change, but because you have the wrong system for change. You do not rise to the level of your goals. You fall to the level of your systems. Here, you'll get a proven system that can take you to new heights. </p><p>Clear is known for his ability to distill complex topics into simple behaviors that can be easily applied to daily life and work. Here, he draws on the most proven ideas from biology, psychology, and neuroscience to create an easy-to-understand guide for making good habits inevitable and bad habits impossible. Along the way, readers will be inspired and entertained with true stories from Olympic gold medalists, award-winning artists, business leaders, life-saving physicians, and star comedians who have used the science of small habits to master their craft and vault to the top of their field. </p><p>Learn how to:<br> <strong><em>*</em>  make time for new habits (even when life gets crazy);<br> </strong><strong><em>  overcome a lack of motivation and willpower;<br> </em></strong><strong>  design your environment to make success easier;<br> </strong>***  get back on track when you fall off course;<br> ...and much more. </p><p><em>Atomic Habits</em> will reshape the way you think about progress and success, and give you the tools and strategies you need to transform your habits--whether you are a team looking to win a championship, an organization hoping to redefine an industry, or simply an individual who wishes to quit smoking, lose weight, reduce stress, or achieve any other goal.</p><p> </p><p>**</p></div>",
        ["identifiers"] = "uuid:urn:uuid:a4cca1c4-44a5-4155-9282-df1a2b0d25ae\
calibre:a4cca1c4-44a5-4155-9282-df1a2b0d25ae\
MOBI-ASIN:B01N5AX61W\
GOOGLE:XfFvDwAAQBAJ\
ISBN:9780735211292\
AMAZON:B01N5AX61W",
        ["keywords"] = "Business & Economics\
Organizational Behavior\
Psychology\
Social Psychology\
Self-Help\
Personal Growth\
General",
        ["language"] = "en",
        ["title"] = "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
    },
    ["floating_punctuation"] = 0,
    ["font_face"] = "Noto Serif",
    ["font_family_fonts"] = {},
    ["handmade_flows_edit_enabled"] = true,
    ["handmade_flows_enabled"] = false,
    ["handmade_toc_edit_enabled"] = true,
    ["handmade_toc_enabled"] = false,
    ["hide_nonlinear_flows"] = false,
    ["highlight_color"] = "gray",
    ["highlight_drawer"] = "lighten",
    ["hyph_force_algorithmic"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyphenation"] = true,
    ["inverse_reading_order"] = false,
    ["last_xpointer"] = "/body/DocFragment[30]/body/div/p[37]/text().386",
    ["page_overlap_style"] = "dim",
    ["partial_md5_checksum"] = "7ac251880252c7f59f4ba9c072943052",
    ["partial_rerendering"] = true,
    ["percent_finished"] = 0.6531914893617,
    ["readermenu_tab_index"] = 7,
    ["show_overlap_enable"] = false,
    ["stats"] = {
        ["authors"] = "James Clear",
        ["highlights"] = 20,
        ["language"] = "en",
        ["notes"] = 0,
        ["pages"] = 470,
        ["performance_in_pages"] = {},
        ["series"] = "N/A",
        ["title"] = "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
    },
    ["summary"] = {
        ["modified"] = "2025-01-02",
        ["status"] = "reading",
    },
    ["text_lang"] = "en-US",
    ["text_lang_embedded_langs"] = true,
    ["toc_ticks_ignored_levels"] = {},
}
